Revert "Prevent java.lang.NoSuchMethodError: er.extensions.eof.ERXKeyFilter.include(Ljava/lang/String;)"
This reverts commit 8e039542a5f2e1d21604a0b3578a7c0f51a45cb9.

I guess I need to think twice about cherry-picking from my branch to integration.