Prevent java.lang.NoSuchMethodError: er.extensions.eof.ERXKeyFilter.include(Ljava/lang/String;)
This error only showed up in deployment on Sun version 1.6.0_27-b07 on Centos Linux but
on Mac build 1.6.0_31-b04-415-11M3646, java correctly called the varargs method with a single element array.
Strange but true.

Interestingly we have a single arg and a varargs variants of the same methods that take ERXKey parameters,
but did not have the single argument include(String keyName) variant. So we workaround this problem by
adding the single argument version for String which matches the method of the same name with ERXKey argument.

The exact versions of java are shown here:

Good version that did not throw NoSuchMethodError
	java version "1.6.0_31"
	Java(TM) SE Runtime Environment (build 1.6.0_31-b04-415-11M3646)
	Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01-415, mixed mode)

Bad version that did throw NoSuchMethodError
	'java version "1.6.0_27"
	Java(TM) SE Runtime Environment (build 1.6.0_27-b07)
	Java HotSpot(TM) 64-Bit Server VM (build 20.2-b06, mixed mode)